allowBuilds:
  '@parcel/watcher': set this to true or false
  msw: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@3.0.124'
  - ai@6.0.196
